---
title: 'Part 2 Random Forest'
author: "Harrison Cradduck, Nick Berry"
date: "`r Sys.Date()`"
output:
  html_document:
    code_folding: show
    df_print: paged
    number_sections: yes
    theme: readable
    toc: yes
    toc_float: yes
    code_download: yes
  word_document:
    toc: no
---

```{r setup, include = FALSE, message = FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
knitr::opts_chunk$set(fig.width = 8, fig.height = 6)

if(require(pacman) == 0)
   {install.packages("pacman")}
pacman::p_load(devtools, caret, cluster, dplyr, fastDummies, leaps, pacman, tidyverse, skimr, fastDummies, GGally, DataExplorer, ggrepel, ggthemes, dslabs, lubridate, stringr, tidytext, purrr)

if (!require(mlba)) {
  library(devtools)
  install_github("gedeck/mlba/mlba", force = TRUE)
}
pacman::p_load(mlba, tidyverse)
```

```{r}
# read in .csv training data file
data_train <- readRDS("final_cleaned_train.rds")
```

```{r}
# read in .csv holdout data file
data_holdout <- readRDS("final_cleaned_holdout.rds")
```


